/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fa",
        "surface-tint": "#2c694e",
        primary: "#0f5238",
        "on-primary-container": "#a8e7c5",
        "inverse-primary": "#95d4b3",
        "surface-variant": "#e1e3e4",
        "primary-container": "#2d6a4f",
        "on-secondary-container": "#255f80",
        "inverse-on-surface": "#f0f1f2",
        error: "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed-dim": "#95d4b3",
        outline: "#707973",
        "on-secondary-fixed": "#001e2e",
        "tertiary-container": "#775b06",
        "secondary-fixed": "#c7e7ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcd579",
        "error-container": "#ffdad6",
        secondary: "#2b6485",
        "secondary-container": "#a3d8fe",
        "on-secondary-fixed-variant": "#064c6b",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#98cdf2",
        "tertiary-fixed-dim": "#e7c268",
        "on-surface-variant": "#404943",
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed": "#002114",
        "tertiary-fixed": "#ffdf96",
        "on-primary-fixed-variant": "#0e5138",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#5a4400",
        "inverse-surface": "#2e3132",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#bfc9c1",
        "on-surface": "#191c1d",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        tertiary: "#5a4400",
        background: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "primary-fixed": "#b1f0ce",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["PlusJakartaSans"],
        "headline-medium": ["PlusJakartaSans_Medium"],
        "headline-semibold": ["PlusJakartaSans_SemiBold"],
        "headline-bold": ["PlusJakartaSans_Bold"],
        "headline-extrabold": ["PlusJakartaSans_ExtraBold"],
        body: ["Manrope"],
        "body-medium": ["Manrope_Medium"],
        "body-semibold": ["Manrope_SemiBold"],
        "body-bold": ["Manrope_Bold"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
};
